### ISSUE TITLE
Ask about license

### ISSUE THREAD

**Issue by sampila** [pzinovkin/emf#1]
Hi @pzinovkin,

Thanks for the great library for read and convert the `EMF` file, I want to ask the license regarding this package, could you give some information?

Best regards,
Alip

**Comment by pzinovkin** [comment]
Hey. License is MIT. Added it here https://github.com/pzinovkin/emf/commit/73329f2e1806639d25b1b1c40a663a21e37b3752

**Comment by sampila** [comment]
Hi @pzinovkin, 
Thank you for the information and reply.
